###------LIBRARY SETUP-----
## @knitr libraries
library(tidyverse)
library(readxl)
library(data.table)
library(HMDHFDplus)
library(tigris)
library(tmap)
library(tmaptools)
library(tidycensus)
library(scales)
library(cowplot)
library(ggrepel)
library(pdftools)
library(ggpubr)
library(getPass)
library(raster)
library(sf)
library(RColorBrewer)